BASE_URL = "https://qa-desk.stand.praktikum-services.ru/"

LOGIN_AND_REGISTRATION_BUTTON_XPATH = "//button[contains(text(), 'Вход и регистрация')]"
NO_ACCOUNT_BUTTON_XPATH = "//button[contains(text(), 'Нет аккаунта')]"
EMAIL_INPUT_NAME = "email"
EMAIL_INPUT_WRAPPER_XPATH = "//input[@name='email']/parent::div"
PASSWORD_INPUT_NAME = "password"
PASSWORD_INPUT_WRAPPER_XPATH = "//input[@name='password']/parent::div"
SUBMIT_PASSWORD_INPUT_NAME = "submitPassword"
SUBMIT_PASSWORD_INPUT_WRAPPER_XPATH = "//input[@name='submitPassword']/parent::div"
CREATE_ACCOUNT_BUTTON_XPATH = "//button[contains(text(), 'Создать аккаунт')]"
LOGIN_BUTTON_XPATH = "//button[contains(text(), 'Войти')]"
LOGOUT_BUTTON_XPATH = "//button[contains(text(), 'Выйти')]"
AVATAR_BUTTON_CSS_XPATH = "//button[@class='circleSmall']"
USER_NAME = "name"
ERROR_MESSAGE_CSS_SELECTOR = '.input_span__yWPqB'
CREATE_AD_BUTTON_XPATH = "//button[contains(text(), 'Разместить объявление')]"
POPUP_CSS_SELECTOR = ".popUp_shell__LuyqR"
TITLE_INPUT_NAME = "name"
INPUT_ARROW_DOWN_BUTTON_CSS_SELECTOR = "button[class*='dropDownMenu_arrowDown']"
DROPDOWN_ITEM_XPATH = "(//div[contains(@class, 'dropDownMenu_options')]//button)[2]"
DESCRIPTION_INPUT_XPATH = "//textarea[@name='description']"
PRICE_INPUT_NAME = "price"
AD_RADIO_XPATH = "//*[@id='root']/div/div[2]/div/form/fieldset/div/div[2]/div"
POST_AD_BUTTON_XPATH = "//button[contains(text(), 'Опубликовать')]"
MY_AD_TITLE_XPATH = "//*[starts-with(@class, 'profilePage_listningBlock')]//div[@class='about']//h2[@class='h2'][1]"#"//*[@id='root']/div/div[2]/div[4]/div/div[1]/div/div/div[1]/h2"
MY_AD_CITY_XPATH = "//*[starts-with(@class, 'profilePage_listningBlock')]//div[@class='about']//h3[@class='h3'][1]" #"//*[@id='root']/div/div[2]/div[4]/div/div[1]/div/div/div[1]/h3"
MY_AD_PRICE_XPATH = "//*[starts-with(@class, 'profilePage_listningBlock')]//div[@class='price']/h2[@class='h2']" #"//*[@id='root']/div/div[2]/div[4]/div/div[1]/div/div/div[2]/h2"
INPUT_SPAN_CSS_SELECTOR = ".input_span__yWPqB"

TEST_EMAIL_1 = "test@ya.ru"
TEST_PASSWORD_1 = "12345"
TEST_EMAIL_2 = "test_3@yandex.ru"
TEST_PASSWORD_2 = "dfgjnSfsg"

EXPECTED_ERROR_BORDER_COLOR = "rgb(255, 105, 114)"
EXPECTED_AD_TITLE = "Красная шапочка"
EXPECTED_AD_DESCRIPTION = "сказка"
EXPECTED_AD_CITY = "Санкт-Петербург"
EXPECTED_AD_PRICE = "5000"
