LOGIN_AND_REGISTRATION_BUTTON_XPATH = "//button[contains(text(), 'Вход и регистрация')]"
NO_ACCOUNT_BUTTON_XPATH = "//button[contains(text(), 'Нет аккаунта')]"
EMAIL_INPUT_NAME = "email"
EMAIL_INPUT_WRAPPER_XPATH = "//*[@id='root']/div/div[2]/div[5]/form/div[2]/div[1]/div/div"
PASSWORD_INPUT_NAME = "password"
PASSWORD_INPUT_WRAPPER_XPATH = "//*[@id='root']/div/div[2]/div[5]/form/div[2]/div[2]/div/div"
SUBMIT_PASSWORD_INPUT_NAME = "submitPassword"
SUBMIT_PASSWORD_INPUT_WRAPPER_XPATH = "//*[@id='root']/div/div[2]/div[5]/form/div[2]/div[3]/div/div"
CREATE_ACCOUNT_BUTTON_XPATH = "//button[contains(text(), 'Создать аккаунт')]"
LOGIN_BUTTON_XPATH = "//button[contains(text(), 'Войти')]"
LOGOUT_BUTTON_XPATH = "//button[contains(text(), 'Выйти')]"
AVATAR_BUTTON_CSS_SELECTOR = ".circleSmall"
AVATAR_BUTTON_XPATH = "//*[@id='root']/div/div[1]/div/div[1]/button"
ERROR_MESSAGE_CSS_SELECTOR = '.input_span__yWPqB'
CREATE_AD_BUTTON_XPATH = "//button[contains(text(), 'Разместить объявление')]"
TITLE_INPUT_NAME = "name"
CITY_INPUT_ARROW_DOWN_BUTTON_XPATH = "//*[@id='root']/div/div[2]/div/form/div[3]/div[1]/button"
CITY_DROPDOWN_ITEM_XPATH = "//*[@id='root']/div/div[2]/div/form/div[3]/div[2]/button[2]"
CATEGORY_INPUT_ARROW_DOWN_BUTTON_XPATH = "//*[@id='root']/div/div[2]/div/form/div[2]/div[2]/div[1]/button"
CATEGORY_DROPDOWN_ITEM_XPATH = "//*[@id='root']/div/div[2]/div/form/div[2]/div[2]/div[2]/button[2]"
DESCRIPTION_INPUT_XPATH = "//*[@id='root']/div/div[2]/div/form/div[4]/div/textarea"
PRICE_INPUT_NAME = "price"
AD_RADIO_XPATH = "//*[@id='root']/div/div[2]/div/form/fieldset/div/div[2]/div"
POST_AD_BUTTON_XPATH = "//button[contains(text(), 'Опубликовать')]"
MY_AD_TITLE_XPATH = "//*[@id='root']/div/div[2]/div[4]/div/div[1]/div/div/div[1]/h2"
MY_AD_CITY_XPATH = "//*[@id='root']/div/div[2]/div[4]/div/div[1]/div/div/div[1]/h3"
MY_AD_PRICE_XPATH = "//*[@id='root']/div/div[2]/div[4]/div/div[1]/div/div/div[2]/h2"
